/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "stm32f401xx.h"
#include "stm32f401xx_gpio.h"
#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(int d) {
	for(int i=0; i<d; i++);
}

#define LD2 5
#define BTN 13

GPIO_Handle_t gpioLed;
GPIO_Handle_t gpioPushBtn;

uint8_t count;
int main(void)
{
	gpioLed.pGPIOx = GPIOA;
	gpioLed.config.GPIO_PinMode = GPIO_MODE_OUTPUT;
	gpioLed.config.GPIO_PinNumber = LD2;
	gpioLed.config.GPIO_PinOutType = GPIO_OTYPE_PP;
	gpioLed.config.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	gpioLed.config.GPIO_PinPuPdConfig = GPIO_NO_PUPD;


	gpioPushBtn.pGPIOx = GPIOC;
	gpioPushBtn.config.GPIO_PinMode = GPIO_MODE_IT_FRT;
	gpioPushBtn.config.GPIO_PinNumber = BTN;
	gpioPushBtn.config.GPIO_PinSpeed = GPIO_SPEED_HIGH;
	gpioPushBtn.config.GPIO_PinPuPdConfig = GPIO_PD;
	//initialize LED
	GPIO_Init(&gpioLed);

	//initialize push button
	GPIO_Init(&gpioPushBtn);

	GPIO_Write_Pin(&gpioLed, LD2, 1);
	for(count=0; count<250; count++) {
		GPIO_Toggle_Pin(&gpioLed, LD2);
		if(GPIO_Read_Pin(&gpioPushBtn, BTN) == 0) {
			continue;
		}
		delay(100000);
	}

	GPIO_IRQ_Config(&gpioPushBtn, 1);

    /* Loop forever */
	for(;;);
}

void EXTI15_10_IRQHandler(void) {
	delay(10000);
	GPIO_Toggle_Pin(&gpioLed, LD2);
	GPIO_IRQ_Handler(BTN);
}
